services:
  nginx:
    image: nginx:alpine
    container_name: mark-web-nginx
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    networks:
      - aotc
    restart: unless-stopped

networks:
  aotc:
    external: true
    name: aotc-dashboard_default
